Make `bundle install` without options work on every platform.
Make the benchmarks group optional due to a contributor's smooth onboarding
process.

The installation of the group benchmarks with the mysql latest version 2.9.1,
fails to build on Ruby >= 2.4 with the following error.

```
Installing activerecord 5.2.4.5
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
...
 current directory:
/opt/hostedtoolcache/Ruby/2.4.10/x64/lib/ruby/gems/2.4.0/gems/mysql-2.9.1/ext/mysql_api
make "DESTDIR="
compiling mysql.c
mysql.c: In function ‘stmt_bind_result’:
mysql.c:1320:74: error: ‘rb_cFixnum’ undeclared (first use in this function);
did you mean ‘rb_isalnum’?
else if (argv[i] == rb_cNumeric || argv[i] == rb_cInteger || argv[i] ==
rb_cFixnum)
^~~~~~~~~~
rb_isalnum
...
```

You can install the group like this when you need it.

```
$ bundle install --with benchmarks
```

See https://bundler.io/man/gemfile.5.html#BLOCK-FORM-OF-SOURCE-GIT-PATH-GROUP-and-PLATFORMS .